---
apiVersion: v1
kind: Namespace
metadata:
  name: fathom
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fathom
  namespace: fathom
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fathom
  namespace: fathom
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: fathom
  template:
    metadata:
      labels:
        app: fathom
    spec:
      containers:
      - name: fathom
        image: usefathom/fathom:version-1.2.1
        env:
        - name: FATHOM_DATABASE_NAME
          value: /data/fathom.db
        - name: FATHOM_GZIP
          value: "true"
        - name: FATHOM_DEBUG
          value: "true"
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - mountPath: /data
          name: fathom-data
      volumes:
      - name: fathom-data
        persistentVolumeClaim:
          claimName: fathom-data
---
apiVersion: v1
kind: Service
metadata:
  name: fathom
  namespace: fathom
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: fathom
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fathom
  namespace: fathom
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  tls:
  - secretName: fathom-tls
    hosts:
    - stats.felixbreuer.me
  rules:
  - host: stats.felixbreuer.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fathom
            port:
              name: http

