---
apiVersion: v1
kind: Namespace
metadata:
  name: travian
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inactive-finder
  namespace: travian
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: inactive-finder
  template:
    metadata:
      labels:
        app: inactive-finder
    spec:
      containers:
      - name: inactive-finder
        image: felixbreuer/travian-inactive-finder:latest
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: inactive-finder
  namespace: travian
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: inactive-finder
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inactive-finder
  namespace: travian
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  tls:
  - secretName: fathom-tls
    hosts:
    - stats.felixbreuer.me
  rules:
  - host: inactive-finder.felixbreuer.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: inactive-finder
            port:
              name: http

