---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- issuer.yaml # for certificates
- ingress.yaml # configure nginx ingress
- breuerfelix.yaml # my own helm chart
- danielkueffler.yaml # daniels blog
- fathom.yaml # website tracking
- inactive-finder.yaml # for legacy travian bots
- paperless-ngx.yaml # document management system
  #- tabby.yaml # code completion
  #- storage.yaml
  #- movie-web.yaml
