---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- issuer.yaml
- danielkueffler.yaml
- fathom.yaml
- inactive-finder.yaml
- tabby.yaml
  #- storage.yaml
  #- movie-web.yaml
