---
apiVersion: v1
kind: Namespace
metadata:
  name: movie-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: movie-web
spec:
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: ghcr.io/movie-web/simple-proxy:latest
        ports:
        - name: http
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: movie-web
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: proxy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy
  namespace: movie-web
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  tls:
  - secretName: proxy-tls
    hosts:
    - movie-web.felixbreuer.me
  rules:
  - host: movie-web.felixbreuer.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: proxy
            port:
              name: http

