---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: flux-system
spec:
  interval: 10m
  install:
    createNamespace: true
  targetNamespace: paperless-ngx
  chart:
    spec:
      chart: paperless-ngx
      version: 0.0.2
      sourceRef:
        kind: HelmRepository
        name: breuerfelix
        namespace: flux-system
  values:
    paperless:
      image:
        name: ghcr.io/paperless-ngx/paperless-ngx
        tag: 2.6.3

      ingress:
        enabled: true
        className: public
        host: paperless.felixbreuer.me

      env:
        - name: PAPERLESS_REDIS
          value: redis://redis:80
        - name: PAPERLESS_TIME_ZONE
          value: Europe/Berlin
        - name: PAPERLESS_OCR_LANGUAGE
          value: deu

      secretRefs:
        - key: PAPERLESS_SECRET_KEY
          name: paperless-ngx
        - key: PAPERLESS_URL
          name: paperless-ngx
        - key: PAPERLESS_ALLOWED_HOSTS
          name: paperless-ngx
        - key: PAPERLESS_ADMIN_USER
          name: paperless-ngx
        - key: PAPERLESS_ADMIN_PASSWORD
          name: paperless-ngx

